ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - name: zig build qemu
    init: ./tools/update-tools.sh
    command:
      ./tools/update-qemu.sh
      && export PATH=./tools/zig:$PATH
      && echo "{\"zig_exe_path\":\"$(pwd)/tools/zig/zig\"}" > ~/.config/zls.json
      && echo zig build qemu ...
      && zig build qemu

vscode:
  extensions:
    - tiehuis.zig@0.2.5:Yj8BTORJw/zERdoSGPf+eQ==
    - augusterame.zls-vscode@1.0.4:ZQxqRwcEt9rZuan0J+3BRQ==
