ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - name: zig build qemu
    init:
      ./tools/update-tools.sh
      && ln -s $(pwd)/tools /workspace/tools
      && export PATH=./tools/zig:$PATH
      && ./build.sh
    command:
      export PATH=./tools/zig:$PATH
      && ./tools/update-qemu.sh
      && mkdir -p ~/.config
      && ln -s $(pwd)/zls.json ~/.config/zls.json
      && echo zig build qemu ...
      && ./qemu.sh

vscode:
  extensions:
    - tiehuis.zig@0.2.5:Yj8BTORJw/zERdoSGPf+eQ==
    - augusterame.zls-vscode@1.0.4:ZQxqRwcEt9rZuan0J+3BRQ==
